apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: sample-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: sample-voting-app