apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: sample-voting-app
spec:
  containers:
    - name: voting-app
      image: ujalasap/voting-app:v1
      ports:
        - containerPort: 80