apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: sample-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: sample-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: sample-voting-app
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379