apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: sample-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: sample-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: sample-voting-app
    spec:
      containers:
        - name: result-app
          image: ujalasap/result-app:v1
          ports:
            - containerPort: 80