apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: sample-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: sample-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: sample-voting-app
    spec:
      containers:
        - name: worker-app
          image: ujalasap/worker-app:v1
      